### PR TITLE
Juan sgw 239 react native code removed in assetsBalanceMonitor.ts file

### PR DESCRIPTION
**Pull request by juanolmedo1**
Ticket: https://constellationnetwork.atlassian.net/browse/SGW-239

### CODE REVIEW

**Comment by AlexBrandes** [comment]
@juanolmedo1 What's up with this old PR? Can this be closed?

**Comment by juanolmedo1** [comment]
> @juanolmedo1 What's up with this old PR? Can this be closed?

We should keep this PR open. It solves a crash on the Chrome Extension. 
The code removed in this PR should be moved somewhere inside the `native` folder.

I'll continue working on this fix after Simplex's integration 😄

**Review by AlexBrandes — APPROVED** [review]
This looks good. Do we have anything similar to NetInfo for web though? It'd be ideal if we could show the same icons in that situation.

**Comment by juanolmedo1** [comment]
> This looks good. Do we have anything similar to NetInfo for web though? It'd be ideal if we could show the same icons in that situation.

@AlexBrandes We're not showing any icon in Mobile for this situation. This code is only checking for NetInfo in background and updating DAG and ETH balances if necessary. I think this logic is already working in Web.

**Pull request merged**
